name: tdd_test_app
description: "A Flutter project to learn Test driven development"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
# Flutter dependencie
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

# Functional Programming package
  dartz: ^0.10.1
# HTTP networking package
  dio: ^5.6.0
# dio API client generator dependencies
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
# Connection checker package
  internet_connection_checker: ^2.0.0
# Comparision and equality package
  equatable: ^2.0.5
# Service locator
  get_it: ^7.7.0
# Logging package
  logger: ^2.4.0
# Mock Test package
  mocktail: ^1.0.4
# Local database package
  hive: ^2.2.3
  path_provider: ^2.1.0

dev_dependencies:
# Flutter dev dependencie
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# dio API client generator dev dependencies
  retrofit_generator: '>=7.0.0 <8.0.0' 
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
